using Microsoft.Extensions.Logging;

namespace NResilience.Extensions.Internal;

/// <summary>
///     The whole vocabulary: every event ID and every message template, in one file, so the contract an
///     alert is built on is reviewable in one place.
///     <para>
///         IDs start at 1000 so that 1 to 999 stay available to the core package and so that no ID collides
///         with the zero an unset <see cref="EventId" /> reports. They are contiguous, and renumbering one is
///         a breaking change to somebody's alert - <c>Event_ids_are_stable</c> is what says so.
///     </para>
///     <para>
///         Every method is generated by <c>[LoggerMessage]</c>, which emits concrete code with no reflection
///         and the <see cref="ILogger.IsEnabled" /> guard that makes a disabled record allocation-free. That
///         is why hand-written <c>logger.Log</c> calls are not permitted here.
///     </para>
/// </summary>
internal static partial class Log
{
    [LoggerMessage(EventId = Codes.AttemptSucceeded, EventName = nameof(Ids.AttemptSucceeded),
        Message = "{Policy} attempt {Attempt} succeeded in {ElapsedMs} ms")]
    internal static partial void AttemptSucceeded(ILogger logger, LogLevel level, string policy, int attempt, long elapsedMs);

    [LoggerMessage(EventId = Codes.AttemptFailed, EventName = nameof(Ids.AttemptFailed),
        Message = "{Policy} attempt {Attempt} failed in {ElapsedMs} ms: {Verdict} {ErrorType}")]
    internal static partial void AttemptFailed(ILogger logger, LogLevel level, Exception? exception, string policy, int attempt, long elapsedMs, string verdict,
        string errorType);

    [LoggerMessage(EventId = Codes.AttemptLimited, EventName = nameof(Ids.AttemptLimited),
        Message = "{Policy} attempt {Attempt} was refused by a local limiter before it left the process")]
    internal static partial void AttemptLimited(ILogger logger, LogLevel level, string policy, int attempt);

    [LoggerMessage(EventId = Codes.Retrying, EventName = nameof(Ids.Retrying),
        Message = "{Policy} waiting {DelayMs} ms before attempt {Attempt} after a {Verdict} outcome")]
    internal static partial void Retrying(ILogger logger, LogLevel level, Exception? exception, string policy, long delayMs, int attempt, string verdict);

    [LoggerMessage(EventId = Codes.CallSucceeded, EventName = nameof(Ids.CallSucceeded), Message = "{Policy} succeeded in {ElapsedMs} ms")]
    internal static partial void CallSucceeded(ILogger logger, LogLevel level, string policy, long elapsedMs);

    [LoggerMessage(EventId = Codes.CallSucceededAfterRetries, EventName = nameof(Ids.CallSucceededAfterRetries),
        Message = "{Policy} succeeded on attempt {Attempt} after {ElapsedMs} ms")]
    internal static partial void CallSucceededAfterRetries(ILogger logger, LogLevel level, string policy, int attempt, long elapsedMs);

    [LoggerMessage(EventId = Codes.NotRetried, EventName = nameof(Ids.NotRetried),
        Message = "{Policy} stopped after attempt {Attempt}: the outcome was classified Permanent")]
    internal static partial void NotRetried(ILogger logger, LogLevel level, Exception? exception, string policy, int attempt);

    [LoggerMessage(
        EventId = Codes.NotRetriedFirstSighting,
        EventName = nameof(Ids.NotRetriedFirstSighting),
        Message =
            "{Policy} did not retry {ErrorType} on attempt {Attempt} because the classifier called it Permanent. If it is transient, give the policy a classifier rule for it.")]
    internal static partial void NotRetriedFirstSighting(ILogger logger, LogLevel level, Exception? exception, string policy, string errorType, int attempt);

    [LoggerMessage(EventId = Codes.Exhausted, EventName = nameof(Ids.Exhausted),
        Message = "{Policy} used all {Attempt} attempts in {ElapsedMs} ms and failed with {ErrorType}")]
    internal static partial void Exhausted(ILogger logger, LogLevel level, Exception? exception, string policy, int attempt, long elapsedMs, string errorType);

    [LoggerMessage(EventId = Codes.DeadlineExceeded, EventName = nameof(Ids.DeadlineExceeded),
        Message = "{Policy} ran out of deadline after {ElapsedMs} ms on attempt {Attempt}")]
    internal static partial void DeadlineExceeded(ILogger logger, LogLevel level, Exception? exception, string policy, long elapsedMs, int attempt);

    [LoggerMessage(
        EventId = Codes.RejectedDependencyUnavailable,
        EventName = nameof(Ids.RejectedDependencyUnavailable),
        Message = "{Policy} refused a call because its circuit breaker is open. Rejections logged quietly since the previous warning: {Suppressed}.")]
    internal static partial void RejectedDependencyUnavailable(ILogger logger, LogLevel level, string policy, int suppressed);

    [LoggerMessage(
        EventId = Codes.RejectedBudgetExhausted,
        EventName = nameof(Ids.RejectedBudgetExhausted),
        Message =
            "{Policy} refused a retry because the retry budget is exhausted, which means this process is retrying harder than the dependency's success rate can fund. Rejections logged quietly since the previous warning: {Suppressed}.")]
    internal static partial void RejectedBudgetExhausted(ILogger logger, LogLevel level, string policy, int suppressed);

    [LoggerMessage(EventId = Codes.RejectedRepeat, EventName = nameof(Ids.RejectedRepeat), Message = "{Policy} refused a call: {Reason}")]
    internal static partial void RejectedRepeat(ILogger logger, LogLevel level, string policy, string reason);

    [LoggerMessage(
        EventId = Codes.BreakerOpened,
        EventName = nameof(Ids.BreakerOpened),
        Message = "{Policy} opened its circuit breaker on attempt {Attempt}. Calls are refused until the break duration elapses.")]
    internal static partial void BreakerOpened(ILogger logger, LogLevel level, string policy, int attempt);

    [LoggerMessage(
        EventId = Codes.BreakerHalfOpened,
        EventName = nameof(Ids.BreakerHalfOpened),
        Message = "{Policy} is probing its dependency: the break duration elapsed and this call is the probe")]
    internal static partial void BreakerHalfOpened(ILogger logger, LogLevel level, string policy);

    [LoggerMessage(EventId = Codes.BreakerClosed, EventName = nameof(Ids.BreakerClosed),
        Message = "{Policy} closed its circuit breaker and is taking traffic again")]
    internal static partial void BreakerClosed(ILogger logger, LogLevel level, string policy);

    [LoggerMessage(
        EventId = Codes.OrphanedWork,
        EventName = nameof(Ids.OrphanedWork),
        Message =
            "{Policy} attempt {Attempt} kept running after its timeout, so that work is still going unobserved. The callback is not honoring the CancellationToken it was handed; NRES001 and NRES002 diagnose this at compile time.")]
    internal static partial void OrphanedWork(ILogger logger, LogLevel level, string policy, int attempt);

    [LoggerMessage(EventId = Codes.OrphanedWorkRepeat, EventName = nameof(Ids.OrphanedWorkRepeat),
        Message = "{Policy} attempt {Attempt} kept running after its timeout")]
    internal static partial void OrphanedWorkRepeat(ILogger logger, LogLevel level, string policy, int attempt);

    [LoggerMessage(
        EventId = Codes.NestedRetry,
        EventName = nameof(Ids.NestedRetry),
        Message =
            "{Policy} is retrying a request that is already inside a retrying client, which multiplies load on the dependency. Remove the retry from one of the two layers.")]
    internal static partial void NestedRetry(ILogger logger, LogLevel level, string policy);

    [LoggerMessage(EventId = Codes.NestedRetryRepeat, EventName = nameof(Ids.NestedRetryRepeat),
        Message = "{Policy} is retrying inside another retrying client")]
    internal static partial void NestedRetryRepeat(ILogger logger, LogLevel level, string policy);

    [LoggerMessage(EventId = Codes.PolicyResolved, EventName = nameof(Ids.PolicyResolved), Message = "{Policy} resolved: {Effective}")]
    internal static partial void PolicyResolved(ILogger logger, LogLevel level, string policy, string effective);

    [LoggerMessage(EventId = Codes.PolicyClassifier, EventName = nameof(Ids.PolicyClassifier), Message = "{Policy} classifier:\n{Rules}")]
    internal static partial void PolicyClassifier(ILogger logger, LogLevel level, string policy, string rules);

    [LoggerMessage(
        EventId = Codes.HedgeStarted,
        EventName = nameof(Ids.HedgeStarted),
        Message = "{Policy} started hedge attempt {Attempt}: the call has been running longer than {ThresholdMs} ms, which is the current quantile of recent calls")]
    internal static partial void HedgeStarted(ILogger logger, LogLevel level, string policy, int attempt, long thresholdMs);

    [LoggerMessage(EventId = Codes.HedgeWon, EventName = nameof(Ids.HedgeWon),
        Message = "{Policy} answered from hedge attempt {Attempt} after {ElapsedMs} ms")]
    internal static partial void HedgeWon(ILogger logger, LogLevel level, string policy, int attempt, long elapsedMs);

    [LoggerMessage(EventId = Codes.HedgeDiscarded, EventName = nameof(Ids.HedgeDiscarded),
        Message = "{Policy} discarded attempt {Attempt} after {ElapsedMs} ms because a sibling answered first")]
    internal static partial void HedgeDiscarded(ILogger logger, LogLevel level, string policy, int attempt, long elapsedMs);

    [LoggerMessage(
        EventId = Codes.AttemptTimeoutAdapted,
        EventName = nameof(Ids.AttemptTimeoutAdapted),
        Message = "{Policy} measured a new per-attempt ceiling of {CeilingMs} ms from recent latency")]
    internal static partial void AttemptTimeoutAdapted(ILogger logger, LogLevel level, string policy, long ceilingMs);

    /// <summary>
    ///     The IDs as constants, so the <c>[LoggerMessage]</c> attributes and the level switches in
    ///     <c>LogListener</c> - both of which need a compile-time constant - name them rather than
    ///     repeat the number.
    /// </summary>
    internal static class Codes
    {
        internal const int AttemptSucceeded = 1000;
        internal const int AttemptFailed = 1001;
        internal const int AttemptLimited = 1002;
        internal const int Retrying = 1003;
        internal const int CallSucceeded = 1004;
        internal const int CallSucceededAfterRetries = 1005;
        internal const int NotRetried = 1006;
        internal const int NotRetriedFirstSighting = 1007;
        internal const int Exhausted = 1008;
        internal const int DeadlineExceeded = 1009;
        internal const int RejectedDependencyUnavailable = 1010;
        internal const int RejectedBudgetExhausted = 1011;
        internal const int RejectedRepeat = 1012;
        internal const int BreakerOpened = 1013;
        internal const int BreakerHalfOpened = 1014;
        internal const int BreakerClosed = 1015;
        internal const int OrphanedWork = 1016;
        internal const int OrphanedWorkRepeat = 1017;
        internal const int NestedRetry = 1018;
        internal const int NestedRetryRepeat = 1019;
        internal const int PolicyResolved = 1020;
        internal const int PolicyClassifier = 1021;
        internal const int HedgeStarted = 1022;
        internal const int HedgeWon = 1023;
        internal const int HedgeDiscarded = 1024;
        internal const int AttemptTimeoutAdapted = 1025;
    }

    /// <summary>
    ///     The IDs, as values, because <see cref="ResilienceLoggingOptions.Level" /> is handed one and a
    ///     caller comparing against a literal wants the name beside it.
    /// </summary>
    internal static class Ids
    {
        internal static readonly EventId AttemptSucceeded = new(Codes.AttemptSucceeded, nameof(AttemptSucceeded));
        internal static readonly EventId AttemptFailed = new(Codes.AttemptFailed, nameof(AttemptFailed));
        internal static readonly EventId AttemptLimited = new(Codes.AttemptLimited, nameof(AttemptLimited));
        internal static readonly EventId Retrying = new(Codes.Retrying, nameof(Retrying));
        internal static readonly EventId CallSucceeded = new(Codes.CallSucceeded, nameof(CallSucceeded));
        internal static readonly EventId CallSucceededAfterRetries = new(Codes.CallSucceededAfterRetries, nameof(CallSucceededAfterRetries));
        internal static readonly EventId NotRetried = new(Codes.NotRetried, nameof(NotRetried));
        internal static readonly EventId NotRetriedFirstSighting = new(Codes.NotRetriedFirstSighting, nameof(NotRetriedFirstSighting));
        internal static readonly EventId Exhausted = new(Codes.Exhausted, nameof(Exhausted));
        internal static readonly EventId DeadlineExceeded = new(Codes.DeadlineExceeded, nameof(DeadlineExceeded));
        internal static readonly EventId RejectedDependencyUnavailable = new(Codes.RejectedDependencyUnavailable, nameof(RejectedDependencyUnavailable));
        internal static readonly EventId RejectedBudgetExhausted = new(Codes.RejectedBudgetExhausted, nameof(RejectedBudgetExhausted));
        internal static readonly EventId RejectedRepeat = new(Codes.RejectedRepeat, nameof(RejectedRepeat));
        internal static readonly EventId BreakerOpened = new(Codes.BreakerOpened, nameof(BreakerOpened));
        internal static readonly EventId BreakerHalfOpened = new(Codes.BreakerHalfOpened, nameof(BreakerHalfOpened));
        internal static readonly EventId BreakerClosed = new(Codes.BreakerClosed, nameof(BreakerClosed));
        internal static readonly EventId OrphanedWork = new(Codes.OrphanedWork, nameof(OrphanedWork));
        internal static readonly EventId OrphanedWorkRepeat = new(Codes.OrphanedWorkRepeat, nameof(OrphanedWorkRepeat));
        internal static readonly EventId NestedRetry = new(Codes.NestedRetry, nameof(NestedRetry));
        internal static readonly EventId NestedRetryRepeat = new(Codes.NestedRetryRepeat, nameof(NestedRetryRepeat));
        internal static readonly EventId PolicyResolved = new(Codes.PolicyResolved, nameof(PolicyResolved));
        internal static readonly EventId PolicyClassifier = new(Codes.PolicyClassifier, nameof(PolicyClassifier));
        internal static readonly EventId HedgeStarted = new(Codes.HedgeStarted, nameof(HedgeStarted));
        internal static readonly EventId HedgeWon = new(Codes.HedgeWon, nameof(HedgeWon));
        internal static readonly EventId HedgeDiscarded = new(Codes.HedgeDiscarded, nameof(HedgeDiscarded));
        internal static readonly EventId AttemptTimeoutAdapted = new(Codes.AttemptTimeoutAdapted, nameof(AttemptTimeoutAdapted));
    }
}
