using Microsoft.Extensions.Logging;

namespace NResilience.Extensions.Internal;

/// <summary>
/// The whole vocabulary: every event ID and every message template, in one file, so the contract an
/// alert is built on is reviewable in one place.
/// <para>
/// IDs start at 1000 so that 1 to 999 stay available to the core package and so that no ID collides
/// with the zero an unset <see cref="EventId"/> reports. They are contiguous, and renumbering one is
/// a breaking change to somebody's alert - <c>Event_ids_are_stable</c> is what says so.
/// </para>
/// <para>
/// Every method is generated by <c>[LoggerMessage]</c>, which emits concrete code with no reflection
/// and the <see cref="ILogger.IsEnabled"/> guard that makes a disabled record allocation-free. That
/// is why hand-written <c>logger.Log</c> calls are not permitted here.
/// </para>
/// </summary>
internal static partial class Log
{
    /// <summary>
    /// The IDs, as values, because <see cref="ResilienceLoggingOptions.Level"/> is handed one and a
    /// caller comparing against a literal wants the name beside it.
    /// </summary>
    internal static class Ids
    {
        internal static readonly EventId AttemptSucceeded = new(1000, nameof(AttemptSucceeded));
        internal static readonly EventId AttemptFailed = new(1001, nameof(AttemptFailed));
        internal static readonly EventId AttemptLimited = new(1002, nameof(AttemptLimited));
        internal static readonly EventId Retrying = new(1003, nameof(Retrying));
        internal static readonly EventId CallSucceeded = new(1004, nameof(CallSucceeded));
        internal static readonly EventId CallSucceededAfterRetries = new(1005, nameof(CallSucceededAfterRetries));
        internal static readonly EventId NotRetried = new(1006, nameof(NotRetried));
        internal static readonly EventId NotRetriedFirstSighting = new(1007, nameof(NotRetriedFirstSighting));
        internal static readonly EventId Exhausted = new(1008, nameof(Exhausted));
        internal static readonly EventId DeadlineExceeded = new(1009, nameof(DeadlineExceeded));
        internal static readonly EventId RejectedDependencyUnavailable = new(1010, nameof(RejectedDependencyUnavailable));
        internal static readonly EventId RejectedBudgetExhausted = new(1011, nameof(RejectedBudgetExhausted));
        internal static readonly EventId RejectedRepeat = new(1012, nameof(RejectedRepeat));
        internal static readonly EventId BreakerOpened = new(1013, nameof(BreakerOpened));
        internal static readonly EventId BreakerHalfOpened = new(1014, nameof(BreakerHalfOpened));
        internal static readonly EventId BreakerClosed = new(1015, nameof(BreakerClosed));
        internal static readonly EventId OrphanedWork = new(1016, nameof(OrphanedWork));
        internal static readonly EventId OrphanedWorkRepeat = new(1017, nameof(OrphanedWorkRepeat));
        internal static readonly EventId NestedRetry = new(1018, nameof(NestedRetry));
        internal static readonly EventId NestedRetryRepeat = new(1019, nameof(NestedRetryRepeat));
        internal static readonly EventId PolicyResolved = new(1020, nameof(PolicyResolved));
        internal static readonly EventId PolicyClassifier = new(1021, nameof(PolicyClassifier));
    }

    [LoggerMessage(EventId = 1000, EventName = nameof(Ids.AttemptSucceeded), Message = "{Policy} attempt {Attempt} succeeded in {ElapsedMs} ms")]
    internal static partial void AttemptSucceeded(ILogger logger, LogLevel level, string policy, int attempt, long elapsedMs);

    [LoggerMessage(EventId = 1001, EventName = nameof(Ids.AttemptFailed), Message = "{Policy} attempt {Attempt} failed in {ElapsedMs} ms: {Verdict} {ErrorType}")]
    internal static partial void AttemptFailed(ILogger logger, LogLevel level, Exception? exception, string policy, int attempt, long elapsedMs, string verdict, string errorType);

    [LoggerMessage(EventId = 1002, EventName = nameof(Ids.AttemptLimited), Message = "{Policy} attempt {Attempt} was refused by a local limiter before it left the process")]
    internal static partial void AttemptLimited(ILogger logger, LogLevel level, string policy, int attempt);

    [LoggerMessage(EventId = 1003, EventName = nameof(Ids.Retrying), Message = "{Policy} waiting {DelayMs} ms before attempt {Attempt} after a {Verdict} outcome")]
    internal static partial void Retrying(ILogger logger, LogLevel level, Exception? exception, string policy, long delayMs, int attempt, string verdict);

    [LoggerMessage(EventId = 1004, EventName = nameof(Ids.CallSucceeded), Message = "{Policy} succeeded in {ElapsedMs} ms")]
    internal static partial void CallSucceeded(ILogger logger, LogLevel level, string policy, long elapsedMs);

    [LoggerMessage(EventId = 1005, EventName = nameof(Ids.CallSucceededAfterRetries), Message = "{Policy} succeeded on attempt {Attempt} after {ElapsedMs} ms")]
    internal static partial void CallSucceededAfterRetries(ILogger logger, LogLevel level, string policy, int attempt, long elapsedMs);

    [LoggerMessage(EventId = 1006, EventName = nameof(Ids.NotRetried), Message = "{Policy} stopped after attempt {Attempt}: the outcome was classified Permanent")]
    internal static partial void NotRetried(ILogger logger, LogLevel level, Exception? exception, string policy, int attempt);

    [LoggerMessage(
        EventId = 1007,
        EventName = nameof(Ids.NotRetriedFirstSighting),
        Message = "{Policy} did not retry {ErrorType} on attempt {Attempt} because the classifier called it Permanent. If it is transient, give the policy a classifier rule for it.")]
    internal static partial void NotRetriedFirstSighting(ILogger logger, LogLevel level, Exception? exception, string policy, string errorType, int attempt);

    [LoggerMessage(EventId = 1008, EventName = nameof(Ids.Exhausted), Message = "{Policy} used all {Attempt} attempts in {ElapsedMs} ms and failed with {ErrorType}")]
    internal static partial void Exhausted(ILogger logger, LogLevel level, Exception? exception, string policy, int attempt, long elapsedMs, string errorType);

    [LoggerMessage(EventId = 1009, EventName = nameof(Ids.DeadlineExceeded), Message = "{Policy} ran out of deadline after {ElapsedMs} ms on attempt {Attempt}")]
    internal static partial void DeadlineExceeded(ILogger logger, LogLevel level, Exception? exception, string policy, long elapsedMs, int attempt);

    [LoggerMessage(
        EventId = 1010,
        EventName = nameof(Ids.RejectedDependencyUnavailable),
        Message = "{Policy} refused a call because its circuit breaker is open. Rejections logged quietly since the previous warning: {Suppressed}.")]
    internal static partial void RejectedDependencyUnavailable(ILogger logger, LogLevel level, string policy, int suppressed);

    [LoggerMessage(
        EventId = 1011,
        EventName = nameof(Ids.RejectedBudgetExhausted),
        Message = "{Policy} refused a retry because the retry budget is exhausted, which means this process is retrying harder than the dependency's success rate can fund. Rejections logged quietly since the previous warning: {Suppressed}.")]
    internal static partial void RejectedBudgetExhausted(ILogger logger, LogLevel level, string policy, int suppressed);

    [LoggerMessage(EventId = 1012, EventName = nameof(Ids.RejectedRepeat), Message = "{Policy} refused a call: {Reason}")]
    internal static partial void RejectedRepeat(ILogger logger, LogLevel level, string policy, string reason);

    [LoggerMessage(
        EventId = 1013,
        EventName = nameof(Ids.BreakerOpened),
        Message = "{Policy} opened its circuit breaker on attempt {Attempt}. Calls are refused until the break duration elapses.")]
    internal static partial void BreakerOpened(ILogger logger, LogLevel level, string policy, int attempt);

    [LoggerMessage(
        EventId = 1014,
        EventName = nameof(Ids.BreakerHalfOpened),
        Message = "{Policy} is probing its dependency: the break duration elapsed and this call is the probe")]
    internal static partial void BreakerHalfOpened(ILogger logger, LogLevel level, string policy);

    [LoggerMessage(EventId = 1015, EventName = nameof(Ids.BreakerClosed), Message = "{Policy} closed its circuit breaker and is taking traffic again")]
    internal static partial void BreakerClosed(ILogger logger, LogLevel level, string policy);

    [LoggerMessage(
        EventId = 1016,
        EventName = nameof(Ids.OrphanedWork),
        Message = "{Policy} attempt {Attempt} kept running after its timeout, so that work is still going unobserved. The callback is not honouring the CancellationToken it was handed; NRES001 and NRES002 diagnose this at compile time.")]
    internal static partial void OrphanedWork(ILogger logger, LogLevel level, string policy, int attempt);

    [LoggerMessage(EventId = 1017, EventName = nameof(Ids.OrphanedWorkRepeat), Message = "{Policy} attempt {Attempt} kept running after its timeout")]
    internal static partial void OrphanedWorkRepeat(ILogger logger, LogLevel level, string policy, int attempt);

    [LoggerMessage(
        EventId = 1018,
        EventName = nameof(Ids.NestedRetry),
        Message = "{Policy} is retrying a request that is already inside a retrying client, which multiplies load on the dependency. Remove the retry from one of the two layers.")]
    internal static partial void NestedRetry(ILogger logger, LogLevel level, string policy);

    [LoggerMessage(EventId = 1019, EventName = nameof(Ids.NestedRetryRepeat), Message = "{Policy} is retrying inside another retrying client")]
    internal static partial void NestedRetryRepeat(ILogger logger, LogLevel level, string policy);

    [LoggerMessage(EventId = 1020, EventName = nameof(Ids.PolicyResolved), Message = "{Policy} resolved: {Effective}")]
    internal static partial void PolicyResolved(ILogger logger, LogLevel level, string policy, string effective);

    [LoggerMessage(EventId = 1021, EventName = nameof(Ids.PolicyClassifier), Message = "{Policy} classifier:\n{Rules}")]
    internal static partial void PolicyClassifier(ILogger logger, LogLevel level, string policy, string rules);
}
